export { default as About } from './About';
export { default as Contact } from './Contact';
export { default as DarkModeToggle } from './DarkModeToggle';
export { default as Education } from './Education';
export { default as Home } from './Home';
export { default as Navbar } from './Navbar';
export { default as Portfolio } from './Portfolio';
export { default as Skills } from './Skills';
export { default as WorkExperience } from './WorkExperience';
